name: Tests

on:
  push:

jobs:
  unittest:
    name: Unit Test
    runs-on: [ubuntu]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.5'
      - name: Running tests
        run: make test
