name: Tests

on:
  push:

jobs:
  unittest:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.x'
      - name: Build
        run: make build
      - name: Test
        run: make test
